scalaVersion := "2.13.3"
libraryDependencies += "org.scalactic"     %% "scalactic"       % "3.2.0"
libraryDependencies += "org.scalatest"     %% "scalatest"       % "3.2.0"
libraryDependencies += "org.scalacheck"    %% "scalacheck"      % "1.14.3"
libraryDependencies += "org.scalatestplus" %% "scalacheck-1-14" % "3.2.0.0"
libraryDependencies += "org.scalamock"     %% "scalamock"       % "5.0.0"
